version: "3.8"

services:
  database:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: laravel
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
  php:
    build:
      context: ./dockerfiles/php
    ports:
      - '18080:80'
    volumes:
      - ./src:/var/www/laravel
      - ./config/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database

volumes:
  postgres_data:
